# Task Definition for Unlimited CCCD Processing System
# Version: 2.0 - Unlimited Processing Support
# Description: Workflow definition for processing unlimited CCCD data

# ------------------------------------------------------------------
# ENVIRONMENT CONFIGURATION - UNLIMITED SETTINGS
# ------------------------------------------------------------------
environment:
  # ---- SỐ LƯỢNG CCCD ----
  # 0 hoặc bỏ qua → *không giới hạn* (đọc từ file input_cccd.txt hoặc sinh vô hạn)
  CCCD_COUNT: 0
  CCCD_PROVINCE_CODE: "001"
  CCCD_BIRTH_YEAR_FROM: 1990
  CCCD_BIRTH_YEAR_TO: 2000

  # ---- XỬ LÝ BATCH ----
  # 0 → "không giới hạn batch size" (xử lý tất cả cùng lúc)
  BATCH_SIZE: 0
  MAX_CONCURRENT_PROCESSING: 0     # 0 → không giới hạn thread/coroutine

  # ---- RETRY / TIMEOUT ----
  RETRY_MAX_ATTEMPTS: 0            # 0 → vô hạn retry (dừng bởi OVERALL_TIMEOUT_MS)
  REQUEST_TIMEOUT_MS: 0             # 0 → không có timeout cố định, chờ phản hồi thực tế
  OVERALL_TIMEOUT_MS: 0             # 0 → workflow chạy tới khi tất cả dữ liệu được xử lý

  # ---- EXCEL EXPORT ----
  MAX_ROWS_PER_SHEET: 0             # 0 → không giới hạn số dòng mỗi sheet
  MAX_SHEETS: 0                     # 0 → không giới hạn số sheet

  # ---- DATA AGGREGATOR ----
  ENABLE_DEDUPLICATION: true
  ENABLE_VALIDATION: true
  AGGREGATOR_MAX_BATCH_SIZE: 0      # 0 → không giới hạn batch size

  # ---- LOGGING ----
  MAX_LOG_ENTRIES: 0                # 0 → không giới hạn log entries

  # ---- CACHE ----
  MAX_CACHE_ENTRIES: 0              # 0 → không giới hạn cache entries

# ------------------------------------------------------------------
# WORKFLOW STEPS - UNLIMITED PROCESSING
# ------------------------------------------------------------------
workflow:
  steps:
    - id: generate_cccd
      name: "Generate CCCD"
      module: cccd_generator
      function: generate
      description: "Tạo CCCD không giới hạn hoặc theo số lượng chỉ định"
      params:
        count: "${environment.CCCD_COUNT}"
        province_code: "${environment.CCCD_PROVINCE_CODE}"
        birth_year_range: [${environment.CCCD_BIRTH_YEAR_FROM}, ${environment.CCCD_BIRTH_YEAR_TO}]
      timeout: "${environment.OVERALL_TIMEOUT_MS}"
      retry:
        attempts: "${environment.RETRY_MAX_ATTEMPTS}"
        delay: 1000

    - id: check_cccd
      name: "Check CCCD"
      module: cccd_checker
      function: check_batch
      description: "Kiểm tra CCCD với API không giới hạn batch"
      params:
        batch_size: "${environment.BATCH_SIZE}"
        concurrent: "${environment.MAX_CONCURRENT_PROCESSING}"
        timeout_ms: "${environment.REQUEST_TIMEOUT_MS}"
        retry_attempts: "${environment.RETRY_MAX_ATTEMPTS}"
      depends_on: ["generate_cccd"]
      timeout: "${environment.OVERALL_TIMEOUT_MS}"

    - id: doanh_nghiep_lookup
      name: "Doanh Nghiep Lookup"
      module: doanh_nghiep_wrapper
      function: fetch_by_cccd
      description: "Tra cứu thông tin doanh nghiệp không giới hạn"
      params:
        max_records: 0  # 0 = không giới hạn
      depends_on: ["check_cccd"]
      timeout: "${environment.OVERALL_TIMEOUT_MS}"

    - id: bhxh_lookup
      name: "BHXH Lookup"
      module: bhxh_wrapper
      function: lookup_bhxh_info
      description: "Tra cứu thông tin BHXH không giới hạn"
      params:
        max_records: 0  # 0 = không giới hạn
      depends_on: ["check_cccd"]
      timeout: "${environment.OVERALL_TIMEOUT_MS}"

    - id: data_aggregation
      name: "Data Aggregation"
      module: data_aggregator
      function: aggregate_from_multiple_sources
      description: "Tổng hợp dữ liệu từ tất cả nguồn không giới hạn"
      params:
        max_batch_size: "${environment.AGGREGATOR_MAX_BATCH_SIZE}"
        enable_deduplication: "${environment.ENABLE_DEDUPLICATION}"
        enable_validation: "${environment.ENABLE_VALIDATION}"
      depends_on: ["doanh_nghiep_lookup", "bhxh_lookup"]
      timeout: "${environment.OVERALL_TIMEOUT_MS}"

    - id: excel_export
      name: "Excel Export"
      module: excel_exporter
      function: export_aggregation_result
      description: "Xuất dữ liệu tổng hợp ra Excel không giới hạn"
      params:
        max_rows_per_sheet: "${environment.MAX_ROWS_PER_SHEET}"
        max_sheets: "${environment.MAX_SHEETS}"
        enable_styling: true
        enable_auto_filter: true
      depends_on: ["data_aggregation"]
      timeout: "${environment.OVERALL_TIMEOUT_MS}"

# ------------------------------------------------------------------
# MONITORING & LOGGING CONFIGURATION
# ------------------------------------------------------------------
monitoring:
  enabled: true
  log_level: "INFO"
  metrics:
    - processing_rate
    - memory_usage
    - error_rate
    - success_rate
  alerts:
    - condition: "error_rate > 0.1"
      message: "High error rate detected"
    - condition: "memory_usage > 80%"
      message: "High memory usage"

# ------------------------------------------------------------------
# SCALING CONFIGURATION
# ------------------------------------------------------------------
scaling:
  auto_scale: true
  min_workers: 1
  max_workers: 0  # 0 = unlimited
  scale_up_threshold: 0.8  # 80% CPU usage
  scale_down_threshold: 0.2  # 20% CPU usage

# ------------------------------------------------------------------
# ERROR HANDLING
# ------------------------------------------------------------------
error_handling:
  max_retries: "${environment.RETRY_MAX_ATTEMPTS}"
  retry_delay: 1000
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    recovery_timeout: 30000
  fallback:
    enabled: true
    strategies:
      - "retry"
      - "degrade"
      - "skip"

# ------------------------------------------------------------------
# PERFORMANCE OPTIMIZATION
# ------------------------------------------------------------------
performance:
  memory_optimization: true
  batch_processing: true
  parallel_processing: true
  caching: true
  compression: true

# ------------------------------------------------------------------
# SECURITY CONFIGURATION
# ------------------------------------------------------------------
security:
  api_key_rotation: true
  rate_limiting: false  # Disabled for unlimited processing
  encryption: true
  audit_logging: true

# ------------------------------------------------------------------
# BACKUP & RECOVERY
# ------------------------------------------------------------------
backup:
  enabled: true
  interval: 3600000  # 1 hour
  retention_days: 30
  compression: true

recovery:
  enabled: true
  checkpoint_interval: 1000  # Save state every 1000 records
  auto_resume: true